# Custom Language File for Launcher Customizer

[ejs.app]
title = "Launcher-Demo"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/3R7XZBzN"

[ejs.settings]
sourceGithubLink = "https://github.com/Emko1219/EmkosResort"
supportLink = "https://github.com/Emko1219/EmkosResort/issues"

[ejs.welcome]
welcomeHeader = "엠코의 휴양지에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
